version: "3.8"

services:
  db:
    image: "postgres:16"
    restart: always
    container_name: "viatabloid-pgsql-container"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: viatabloid_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 420690

  backend:
    build:
      context: ./viatabloid-backend
      dockerfile: Dockerfile
    image: "viatabloid-backend:v1.0.0"
    container_name: "viatabloid-backend-container"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/viatabloid_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 420690
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_WEB_CORS_ALLOWED-ORIGINS: http://localhost:5173

  frontend:
    build:
      context: ./viatabloid-frontend
      dockerfile: Dockerfile
    image: "viatabloid-frontend:v1.0.0"
    container_name: "viatabloid-frontend-container"
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
